# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://otaviormachado.github.io" # the base hostname & protocol for your site

# User settings
username: Code Bucket
user_description: Eternal learner, Software Developer, Team Enabler and occasional Pokémon Master. I play with words and with code — and I want to make the world a better place.
user_title: Otávio Machado
email: otaviormachado@gmail.com
twitter_username: _otaviomachado
github_username:  otaviormachado
gplus_username: otaviomachado
disqus_username: otaviormachado

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
